# Generated by Django 5.2.4 on 2025-09-23 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0007_materialtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=100, null=True, verbose_name='大小')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='重量')),
                ('detailed_description', models.TextField(blank=True, null=True, verbose_name='詳細說明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='material_spec_images/', verbose_name='圖片')),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='inventory.material', verbose_name='物料')),
            ],
        ),
    ]
