# Generated by Django 5.2.4 on 2025-09-04 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='庫位')),
                ('bin', models.CharField(max_length=100, verbose_name='儲格')),
                ('material_code', models.CharField(max_length=100, unique=True, verbose_name='物料')),
                ('material_description', models.CharField(max_length=200, verbose_name='物料說明')),
                ('system_quantity', models.IntegerField(verbose_name='系統庫存數量')),
                ('last_counted_date', models.DateTimeField(blank=True, null=True, verbose_name='上次盤點日期')),
            ],
            options={
                'verbose_name': '主物料',
                'verbose_name_plural': '主庫存清單',
            },
        ),
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocktake_id', models.CharField(max_length=50, unique=True, verbose_name='盤點單號')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('status', models.CharField(choices=[('進行中', '進行中'), ('已完成', '已完成')], default='進行中', max_length=10, verbose_name='狀態')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='建立人員')),
            ],
            options={
                'verbose_name': '盤點單',
                'verbose_name_plural': '盤點單列表',
            },
        ),
        migrations.CreateModel(
            name='StocktakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity_on_record', models.IntegerField(verbose_name='當時系統數量')),
                ('counted_quantity', models.IntegerField(blank=True, null=True, verbose_name='實際盤點數量')),
                ('status', models.CharField(choices=[('待盤點', '待盤點'), ('已盤點', '已盤點')], default='待盤點', max_length=10, verbose_name='狀態')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.material', verbose_name='物料')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktake', verbose_name='盤點單')),
            ],
            options={
                'verbose_name': '盤點品項',
                'verbose_name_plural': '盤點品項列表',
            },
        ),
    ]
