# Generated by Django 5.2.4 on 2025-09-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='盤點單名稱'),
        ),
    ]
