# Generated by Django 5.2.4 on 2025-09-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktake_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='latest_counted_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='最新盤點數量'),
        ),
        migrations.AddField(
            model_name='material',
            name='latest_difference',
            field=models.IntegerField(blank=True, null=True, verbose_name='最新差異'),
        ),
    ]
