# Generated by Django 5.2.4 on 2025-09-04 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_material_latest_counted_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='latest_difference',
        ),
    ]
