# Generated by Django 5.2.4 on 2025-09-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_material_latest_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktake',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='筆記'),
        ),
    ]
