# Generated by Django 5.2.4 on 2025-09-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stocktake_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktake',
            name='notes',
        ),
    ]
