# Generated by Django 5.2.4 on 2025-09-12 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_stocktake_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ALLOCATION', '撥料'), ('RETURN', '退料'), ('MANUAL_UPDATE', '手動修改'), ('INITIAL_IMPORT', '初始匯入')], max_length=20, verbose_name='操作類型')),
                ('quantity_change', models.IntegerField(verbose_name='變動數量')),
                ('new_system_quantity', models.IntegerField(verbose_name='操作後總量')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='備註')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.material', verbose_name='物料')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人員')),
            ],
            options={
                'verbose_name': '物料交易紀錄',
                'verbose_name_plural': '物料交易紀錄',
                'ordering': ['-timestamp'],
            },
        ),
    ]
