# Generated by Django 5.2.4 on 2025-11-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_material_purchaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='purchaser',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='採購員'),
        ),
    ]
