from .requisition_management_views import *
from .material_completeness_views import *
from .auth_views import *
from .dispatch_views import *
from .image_views import *
from .material_data_views import *
from .material_export_views import *
from .material_upload_views import *
from .material_demand_views import *
from .work_order_views import *
