# Generated by Django 5.2.4 on 2025-09-03 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_number', models.CharField(max_length=100, unique=True, verbose_name='物料')),
                ('storage_bin', models.CharField(blank=True, max_length=100, null=True, verbose_name='儲格')),
                ('stock_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='庫存數量')),
            ],
            options={
                'verbose_name': '庫存',
                'verbose_name_plural': '庫存',
            },
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='機型名稱')),
            ],
            options={
                'verbose_name': '機型',
                'verbose_name_plural': '機型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialListVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳人員')),
            ],
            options={
                'verbose_name': '物料清單版本',
                'verbose_name_plural': '物料清單版本',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='投料點名稱')),
                ('machine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_types', to='requisitions.machinemodel', verbose_name='所屬機型')),
            ],
            options={
                'verbose_name': '投料點',
                'verbose_name_plural': '投料點',
                'ordering': ['machine_model', 'name'],
                'unique_together': {('name', 'machine_model')},
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='訂單單號')),
                ('request_date', models.DateField(db_index=True, verbose_name='需求日期')),
                ('process_type', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='需求流程')),
                ('status', models.CharField(choices=[('pending', '待撥料'), ('materials_confirmed', '物料已確認'), ('completed', '已完成')], db_index=True, default='pending', max_length=20, verbose_name='狀態')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('material_confirmed_date', models.DateTimeField(blank=True, null=True, verbose_name='物料確認時間')),
                ('sign_off_date', models.DateTimeField(blank=True, null=True, verbose_name='最終簽收時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions_applied', to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
                ('current_material_list_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_requisitions', to='requisitions.materiallistversion', verbose_name='當前物料清單版本')),
                ('material_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_material_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='物料確認人員')),
                ('sign_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_signed_off', to=settings.AUTH_USER_MODEL, verbose_name='最終簽收人員')),
            ],
            options={
                'verbose_name': '撥料申請單',
                'verbose_name_plural': '撥料申請單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='materiallistversion',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_versions', to='requisitions.requisition', verbose_name='所屬撥料單'),
        ),
        migrations.CreateModel(
            name='RequisitionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='requisition_images/', verbose_name='撥料單圖片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='requisitions.requisition', verbose_name='所屬撥料單')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳人員')),
            ],
            options={
                'verbose_name': '撥料單圖片',
                'verbose_name_plural': '撥料單圖片',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=100, verbose_name='訂單單號')),
                ('material_number', models.CharField(db_index=True, max_length=100, verbose_name='物料')),
                ('item_name', models.CharField(max_length=255, verbose_name='品名')),
                ('required_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='需求數量')),
                ('confirmed_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='已撥料數量')),
                ('is_signed_off', models.BooleanField(default=False, verbose_name='已簽收')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_order_materials', to='requisitions.machinemodel', verbose_name='機型')),
                ('process_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requisitions.processtype', verbose_name='投料點')),
            ],
            options={
                'verbose_name': '訂單主物料清單',
                'verbose_name_plural': '訂單主物料清單',
                'ordering': ['order_number', 'process_type', 'material_number'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='訂單單號')),
                ('material_number', models.CharField(db_index=True, max_length=100, verbose_name='物料')),
                ('item_name', models.CharField(max_length=255, verbose_name='品名')),
                ('required_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='需求數量')),
                ('stock_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='庫存數量')),
                ('storage_bin', models.CharField(blank=True, max_length=100, null=True, verbose_name='儲格')),
                ('confirmed_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='確認撥料數量')),
                ('is_signed_off', models.BooleanField(default=False, verbose_name='最終簽收已確認')),
                ('material_list_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requisitions.materiallistversion', verbose_name='物料清單版本')),
                ('source_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_items', to='requisitions.workordermaterial', verbose_name='來源主物料')),
            ],
            options={
                'verbose_name': '撥料物料明細',
                'verbose_name_plural': '撥料物料明細',
            },
        ),
        migrations.AddConstraint(
            model_name='requisition',
            constraint=models.UniqueConstraint(fields=('order_number', 'process_type'), name='unique_order_per_process'),
        ),
        migrations.AddConstraint(
            model_name='workordermaterial',
            constraint=models.UniqueConstraint(fields=('order_number', 'material_number', 'machine_model'), name='unique_material_per_order_and_model'),
        ),
    ]
