# Generated by Django 5.2.4 on 2025-09-12 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderMaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ALLOCATION', '撥料'), ('RETURN', '退料'), ('MANUAL_UPDATE', '手動修改')], max_length=20, verbose_name='操作類型')),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='變動數量')),
                ('new_confirmed_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='操作後總撥料數量')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='備註')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人員')),
                ('work_order_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='requisitions.workordermaterial', verbose_name='訂單物料')),
            ],
            options={
                'verbose_name': '訂單物料交易紀錄',
                'verbose_name_plural': '訂單物料交易紀錄',
                'ordering': ['-timestamp'],
            },
        ),
    ]
