# Generated by Django 5.2.4 on 2025-09-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0002_workordermaterialtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='current_material_list_version',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='material_confirmed_by',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='material_confirmed_date',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='sign_off_by',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='sign_off_date',
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('completed', '已處理')], db_index=True, default='pending', max_length=20, verbose_name='狀態'),
        ),
    ]
