# Generated by Django 5.2.4 on 2025-09-12 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0003_remove_requisition_current_material_list_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordermaterial',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='品名'),
        ),
        migrations.AlterField(
            model_name='workordermaterial',
            name='material_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='物料'),
        ),
    ]
