# Generated by Django 5.2.4 on 2025-09-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0004_alter_workordermaterial_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='dispatch_performed',
            field=models.BooleanField(default=False, verbose_name='已執行撥料'),
        ),
    ]
