# Generated by Django 5.2.4 on 2025-09-13 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0005_requisition_dispatch_performed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderMaterialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_order_material_images/', verbose_name='訂單物料圖片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳人員')),
                ('work_order_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='requisitions.workordermaterial', verbose_name='所屬訂單物料')),
            ],
            options={
                'verbose_name': '訂單物料圖片',
                'verbose_name_plural': '訂單物料圖片',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
