# Generated by Django 5.2.4 on 2025-09-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0006_workordermaterialimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordermaterialimage',
            name='work_order_material',
        ),
        migrations.AddField(
            model_name='workordermaterialimage',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_order_material_images', to='requisitions.requisition', verbose_name='所屬撥料單'),
        ),
    ]
