# Generated by Django 5.2.4 on 2025-09-13 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0007_remove_workordermaterialimage_work_order_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterialimage',
            name='process_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='requisitions.processtype', verbose_name='投料點'),
        ),
    ]
