# Generated by Django 5.2.4 on 2025-09-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0008_workordermaterialimage_process_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否啟用'),
        ),
    ]
