# Generated by Django 5.2.4 on 2025-09-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0009_workordermaterial_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workordermaterial',
            name='unique_material_per_order_and_model',
        ),
    ]
