# Generated by Django 5.2.4 on 2025-09-18 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0010_remove_workordermaterial_unique_material_per_order_and_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='material_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_material_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='物料確認人員'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='material_confirmed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='物料確認日期'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='sign_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_signed_off', to=settings.AUTH_USER_MODEL, verbose_name='最終簽收人員'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='sign_off_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終簽收日期'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('materials_confirmed', '物料已確認'), ('completed', '已處理')], db_index=True, default='pending', max_length=20, verbose_name='狀態'),
        ),
    ]
