# Generated by Django 5.2.4 on 2025-09-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0011_requisition_material_confirmed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='是否已歸檔'),
        ),
    ]
