# Generated by Django 5.2.4 on 2025-09-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0012_requisition_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='estimated_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='預計入料日期'),
        ),
    ]
