# Generated by Django 5.2.4 on 2025-09-25 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0013_workordermaterial_estimated_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='current_material_list_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='requisitions.materiallistversion', verbose_name='當前物料清單版本'),
        ),
    ]
