# Generated by Django 5.2.4 on 2025-10-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0014_requisition_current_material_list_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='demand_date',
            field=models.DateField(blank=True, null=True, verbose_name='需求日期'),
        ),
    ]
