# Generated by Django 5.2.4 on 2025-11-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0015_workordermaterial_demand_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('awaiting_dispatch', '待撥料人員處理'), ('materials_confirmed', '物料已確認'), ('completed', '已處理')], db_index=True, default='pending', max_length=20, verbose_name='狀態'),
        ),
    ]
