# Generated by Django 5.2.4 on 2025-11-10 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0016_alter_requisition_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='current_material_list_version',
        ),
        migrations.RemoveField(
            model_name='requisitionitem',
            name='material_list_version',
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='dispatch_status',
            field=models.CharField(blank=True, choices=[('dispatched', '已撥料'), ('backordered', '欠料')], max_length=20, null=True, verbose_name='撥料狀態'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requisitions.requisition', verbose_name='所屬撥料單'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('demand_submitted', '需求已提交'), ('dispatch_in_progress', '撥料中'), ('dispatch_completed', '撥料已完成'), ('signed_off', '已簽收'), ('archived', '已歸檔')], db_index=True, default='demand_submitted', max_length=20, verbose_name='狀態'),
        ),
        migrations.DeleteModel(
            name='MaterialListVersion',
        ),
    ]
