# Generated by Django 5.2.4 on 2025-11-10 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0017_remove_requisition_current_material_list_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='sign_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_items_signed_off', to=settings.AUTH_USER_MODEL, verbose_name='簽收人員'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='sign_off_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='簽收日期'),
        ),
    ]
