# Generated by Django 5.2.4 on 2025-11-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0018_requisitionitem_sign_off_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='工單單號')),
                ('is_archived', models.BooleanField(default=False, verbose_name='是否已歸檔')),
                ('status_message', models.CharField(blank=True, max_length=255, null=True, verbose_name='工單現況')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '工單',
                'verbose_name_plural': '工單',
                'ordering': ['-updated_at'],
            },
        ),
    ]
