# Generated by Django 5.2.4 on 2025-11-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0019_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='shipping_date',
            field=models.DateField(blank=True, null=True, verbose_name='出貨日期'),
        ),
    ]
