# Generated by Django 5.2.4 on 2025-11-25 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0020_workorder_shipping_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='is_kit',
            field=models.BooleanField(default=False, verbose_name='是否為台份(Kit)'),
        ),
        migrations.AddField(
            model_name='processtype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='requisitions.processtype', verbose_name='上層投料點'),
        ),
    ]
