# Generated by Django 5.2.4 on 2026-01-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0021_processtype_is_kit_processtype_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoUploadConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('inventory', '庫存資料 (Inventory)'), ('order_model', '訂單機型 (Order Models)'), ('material_details', '物料明細 (Material Details)')], max_length=50, unique=True, verbose_name='上傳類型')),
                ('file_path', models.CharField(help_text='請輸入完整檔案路徑，例如 C:\\SAP\\inventory.xlsx', max_length=255, verbose_name='檔案路徑')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='最後執行時間')),
                ('last_status', models.CharField(blank=True, max_length=255, verbose_name='最後執行狀態')),
            ],
            options={
                'verbose_name': '自動上傳設定',
                'verbose_name_plural': '自動上傳設定',
            },
        ),
    ]
