# Generated by Django 5.2.4 on 2026-01-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0022_autouploadconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='autouploadconfig',
            name='last_processed_mtime',
            field=models.FloatField(blank=True, null=True, verbose_name='最後處理檔案修改時間'),
        ),
    ]
