# Generated by Django 5.2.4 on 2026-01-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0023_autouploadconfig_last_processed_mtime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autouploadconfig',
            options={'ordering': ['priority'], 'verbose_name': '自動上傳設定', 'verbose_name_plural': '自動上傳設定'},
        ),
        migrations.AddField(
            model_name='autouploadconfig',
            name='priority',
            field=models.IntegerField(default=0, help_text='數字越小越先執行', verbose_name='執行順序'),
        ),
    ]
