# Generated by Django 5.2.4 on 2026-01-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0024_alter_autouploadconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='alert_message',
            field=models.TextField(blank=True, null=True, verbose_name='警示訊息'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='has_alert',
            field=models.BooleanField(default=False, verbose_name='有需求變更警示'),
        ),
    ]
