# Generated by Django 5.2.4 on 2026-01-15 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0025_requisition_alert_message_requisition_has_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProcessTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_prefix', models.CharField(db_index=True, max_length=100, verbose_name='物料前綴/號碼')),
                ('machine_model_name', models.CharField(db_index=True, max_length=100, verbose_name='機型名稱')),
                ('process_type_name', models.CharField(max_length=100, verbose_name='投料點名稱')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新人員')),
            ],
            options={
                'verbose_name': '物料投料點規則 (學習紀錄)',
                'verbose_name_plural': '物料投料點規則 (學習紀錄)',
                'unique_together': {('material_prefix', 'machine_model_name')},
            },
        ),
    ]
