# Generated by Django 5.2.4 on 2026-01-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0026_materialprocesstyperule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='materialprocesstyperule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='materialprocesstyperule',
            name='parent_material_desc_keyword',
            field=models.CharField(blank=True, help_text='若填寫，則只有當上層物料說明包含此關鍵字時才套用', max_length=100, null=True, verbose_name='上層說明關鍵字'),
        ),
        migrations.AlterUniqueTogether(
            name='materialprocesstyperule',
            unique_together={('material_prefix', 'machine_model_name', 'parent_material_desc_keyword')},
        ),
    ]
