# Generated by Django 5.2.4 on 2026-01-27 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0027_alter_materialprocesstyperule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='is_supplementary',
            field=models.BooleanField(default=False, verbose_name='是否為補撥'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplementary_items', to='requisitions.requisitionitem', verbose_name='原始項目'),
        ),
    ]
