# Generated by Django 5.2.4 on 2026-01-27 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0028_requisitionitem_is_supplementary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationProcessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_description', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='作業說明')),
                ('process_type', models.CharField(max_length=50, verbose_name='投料點')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='設定人員')),
            ],
            options={
                'verbose_name': '作業說明投料點規則',
                'verbose_name_plural': '作業說明投料點規則',
                'ordering': ['operation_description'],
            },
        ),
    ]
