# Generated by Django 5.2.4 on 2026-01-27 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0029_operationprocessrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='material_type',
            field=models.CharField(choices=[('finished', '成品'), ('semi_finished', '半成品')], db_index=True, default='finished', max_length=20, verbose_name='物料類型'),
        ),
        migrations.CreateModel(
            name='SemiFinishedProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='投料點名稱')),
                ('color', models.CharField(default='#6366F1', max_length=20, verbose_name='顯示顏色')),
                ('order', models.IntegerField(default=0, verbose_name='排序順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_semi_process_types', to=settings.AUTH_USER_MODEL, verbose_name='建立人員')),
            ],
            options={
                'verbose_name': '半成品投料點',
                'verbose_name_plural': '半成品投料點',
                'ordering': ['order', 'name'],
            },
        ),
    ]
