# Generated by Django 5.2.4 on 2026-01-28 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0030_workordermaterial_material_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requisition',
            name='unique_order_per_process',
        ),
        migrations.AddField(
            model_name='requisition',
            name='requisition_type',
            field=models.CharField(choices=[('finished', '成品'), ('semi_finished', '半成品')], db_index=True, default='finished', max_length=20, verbose_name='申請單類型'),
        ),
        migrations.AddConstraint(
            model_name='requisition',
            constraint=models.UniqueConstraint(fields=('order_number', 'process_type', 'requisition_type'), name='unique_order_per_process_type'),
        ),
    ]
