# Generated by Django 5.2.4 on 2026-01-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0032_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autouploadconfig',
            name='upload_type',
            field=models.CharField(choices=[('inventory', '庫存資料 (Inventory)'), ('order_model', '訂單機型 (Order Models)'), ('material_details', '物料明細 (Material Details)'), ('semi_finished', '半成品資料 (Semi-Finished)')], max_length=50, unique=True, verbose_name='上傳類型'),
        ),
    ]
