# Generated by Django 5.2.4 on 2026-03-02 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0034_alter_autouploadconfig_upload_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionViewPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='申請單擁有者')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_permissions_received', to=settings.AUTH_USER_MODEL, verbose_name='被授權查看者')),
            ],
            options={
                'verbose_name': '申請單查看授權',
                'verbose_name_plural': '申請單查看授權',
                'unique_together': {('owner', 'viewer')},
            },
        ),
    ]
