# Generated by Django 5.2.4 on 2026-03-04 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0035_requisitionviewpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUserCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(verbose_name='原始問題')),
                ('incorrect_response', models.TextField(verbose_name='錯誤回答')),
                ('correction_text', models.TextField(verbose_name='使用者修正建議')),
                ('is_active', models.BooleanField(default=True, help_text='關閉則 AI 不會參考此條修正', verbose_name='是否生效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_corrections', to=settings.AUTH_USER_MODEL, verbose_name='修正者')),
            ],
            options={
                'verbose_name': 'AI 修正紀錄',
                'verbose_name_plural': 'AI 修正紀錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
