# Generated by Django 5.2.4 on 2026-03-04 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0036_aiusercorrection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionShareGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='群組名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('members', models.ManyToManyField(related_name='requisition_share_groups', to=settings.AUTH_USER_MODEL, verbose_name='群組成員')),
            ],
            options={
                'verbose_name': '申請單共享群組',
                'verbose_name_plural': '申請單共享群組',
            },
        ),
    ]
