# Generated by Django 5.2.4 on 2026-03-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0037_requisitionsharegroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequisitionViewPermission',
        ),
    ]
