# Generated by Django 5.2.4 on 2026-03-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0039_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='過期時間'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_system_generated',
            field=models.BooleanField(default=False, verbose_name='系統自動產生'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_publish_announcements',
            field=models.BooleanField(default=False, verbose_name='可發佈公告'),
        ),
    ]
