# Generated by Django 5.2.4 on 2026-04-02 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0040_announcement_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderMaterialProcessTypeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_process_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='原投料點')),
                ('new_process_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='新投料點')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人員')),
                ('work_order_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_type_logs', to='requisitions.workordermaterial', verbose_name='訂單物料')),
            ],
            options={
                'verbose_name': '物料投料點異動紀錄',
                'verbose_name_plural': '物料投料點異動紀錄',
                'ordering': ['-timestamp'],
            },
        ),
    ]
