# Generated by Django 5.2.4 on 2026-04-10 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0041_workordermaterialprocesstypelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='撥料時間'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_dispatched', to=settings.AUTH_USER_MODEL, verbose_name='撥料人員'),
        ),
    ]
