# Generated by Django 5.2.4 on 2026-04-10 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0042_requisitionitem_dispatched_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='alert_dismissed',
            field=models.BooleanField(default=False, verbose_name='警示已解除'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='alert_dismissed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='警示解除時間'),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='alert_dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_alert_dismissed', to=settings.AUTH_USER_MODEL, verbose_name='警示解除人員'),
        ),
    ]
