# Generated by Django 5.2.4 on 2026-04-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0043_requisitionitem_alert_dismissed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='客戶名稱'),
        ),
        migrations.AlterField(
            model_name='autouploadconfig',
            name='upload_type',
            field=models.CharField(choices=[('inventory', '庫存資料 (Inventory)'), ('order_model', '訂單機型 (Order Models)'), ('material_details', '物料明細 (Material Details)'), ('semi_finished', '半成品資料 (Semi-Finished)'), ('semi_finished_model_db', '半成品機型資料庫 (Semi-Finished Model DB)'), ('shipping_customer', '出貨客戶資料 (Shipping & Customer)')], max_length=50, unique=True, verbose_name='上傳類型'),
        ),
    ]
