# Generated by Django 5.2.4 on 2026-04-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0044_add_customer_name_and_shipping_customer_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='sap_sync_issue',
            field=models.BooleanField(default=False, verbose_name='SAP扣帳異常'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='sap_sync_issue_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='異常發生時間'),
        ),
        migrations.AddField(
            model_name='workordermaterial',
            name='sap_withdrawn_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='SAP已領料數量'),
        ),
    ]
