# Generated by Django 5.2.4 on 2026-04-28 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0045_workordermaterial_sap_sync_issue_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
