# Generated by Django 5.2.4 on 2026-05-06 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0047_alter_autouploadconfig_upload_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='has_issue',
            field=models.BooleanField(default=False, verbose_name='有未解決異況'),
        ),
        migrations.CreateModel(
            name='RequisitionItemIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='回報時間')),
                ('description', models.TextField(verbose_name='異況說明')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='已解除')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解除時間')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='結案紀錄')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL, verbose_name='回報人')),
                ('requisition_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='requisitions.requisitionitem', verbose_name='所屬明細')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL, verbose_name='解除人')),
            ],
            options={
                'verbose_name': '明細異況紀錄',
                'verbose_name_plural': '明細異況紀錄',
                'ordering': ['-reported_at'],
            },
        ),
    ]
