# Generated by Django 5.2.4 on 2026-05-13 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0048_requisitionitem_has_issue_requisitionitemissue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_special_request',
            field=models.BooleanField(default=False, verbose_name='可使用成品特殊申請功能'),
        ),
        migrations.CreateModel(
            name='UserSelectedMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_number', models.CharField(db_index=True, max_length=100, verbose_name='物料號碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_materials', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者自選物料',
                'verbose_name_plural': '使用者自選物料',
                'unique_together': {('user', 'material_number')},
            },
        ),
    ]
