# Generated by Django 5.2.4 on 2026-05-13 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0049_userprofile_can_access_special_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='demand_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_demanded', to=settings.AUTH_USER_MODEL, verbose_name='需求人員'),
        ),
    ]
