# Generated by Django 5.2.4 on 2026-05-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0050_requisition_demand_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='parent_material_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='上層物料說明'),
        ),
    ]
