# Generated by Django 5.2.4 on 2026-05-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisitions', '0051_workordermaterial_parent_material_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermaterial',
            name='operation_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='作業說明'),
        ),
    ]
