# Generated by Django 5.2.4 on 2026-03-16 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='需求內容')),
                ('request_photo', models.ImageField(blank=True, null=True, upload_to='peer_requests/requests/', verbose_name='需求照片')),
                ('request_date', models.DateField(verbose_name='需求日期')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='撥料日期')),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='peer_requests/deliveries/', verbose_name='撥料照片')),
                ('delivery_reply', models.TextField(blank=True, null=True, verbose_name='收件人回覆文字')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('shipped', '已撥料'), ('closed', '已結案')], default='pending', max_length=20, verbose_name='狀態')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='結案時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='收件人')),
            ],
            options={
                'verbose_name': '對等物料申請',
                'verbose_name_plural': '對等物料申請',
                'ordering': ['-created_at'],
            },
        ),
    ]
