# Generated by Django 5.2.4 on 2026-03-17 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peerrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '物料申請', 'verbose_name_plural': '物料申請'},
        ),
    ]
