# Generated by Django 5.2.4 on 2026-03-25 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_requests', '0002_alter_peerrequest_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='peerrequest',
            name='cc_users',
            field=models.ManyToManyField(blank=True, related_name='peer_requests_cced', to=settings.AUTH_USER_MODEL, verbose_name='副本通知(CC)'),
        ),
    ]
