# Generated by Django 5.2.4 on 2026-03-25 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_requests', '0003_peerrequest_cc_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerRequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='模板名稱')),
                ('description', models.TextField(verbose_name='預設需求內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('cc_users', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='預設副本(CC)')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='預設收件人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_request_templates', to=settings.AUTH_USER_MODEL, verbose_name='擁有者')),
            ],
            options={
                'verbose_name': '物料申請模板',
                'verbose_name_plural': '物料申請模板',
                'ordering': ['-created_at'],
            },
        ),
    ]
