# Generated by Django 5.2.4 on 2026-04-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_requests', '0004_peerrequesttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerrequest',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='預計完成日期'),
        ),
        migrations.AlterField(
            model_name='peerrequest',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='實際撥料日期'),
        ),
        migrations.AlterField(
            model_name='peerrequest',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('shipped', '已撥料'), ('closed', '已結案')], default='pending', max_length=20, verbose_name='狀態'),
        ),
    ]
