# Generated by Django 5.2.4 on 2026-03-17 03:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockPickingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(max_length=50, unique=True, verbose_name='任務單號')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
            ],
            options={
                'verbose_name': '模擬揀料單',
                'verbose_name_plural': '模擬揀料單',
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：A-01, B-02-03', max_length=50, unique=True, verbose_name='儲位代號')),
                ('x_coordinate', models.FloatField(default=0.0, help_text='空間相對 X 座標', verbose_name='X 座標')),
                ('y_coordinate', models.FloatField(default=0.0, help_text='空間相對 Y 座標', verbose_name='Y 座標')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='位置描述')),
            ],
            options={
                'verbose_name': '倉儲節點',
                'verbose_name_plural': '倉儲節點',
            },
        ),
        migrations.CreateModel(
            name='MockPickingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, verbose_name='物料名稱')),
                ('quantity_required', models.PositiveIntegerField(verbose_name='應拿數量')),
                ('status', models.CharField(choices=[('pending', '待拿取'), ('picked', '已撥料'), ('shortage', '缺料/跳過')], default='pending', max_length=20, verbose_name='當前狀態')),
                ('picked_at', models.DateTimeField(blank=True, null=True, verbose_name='處理時間')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='interactive_picking.mockpickingtask')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picking_items', to='interactive_picking.warehouselocation')),
            ],
            options={
                'verbose_name': '模擬揀料項目',
                'verbose_name_plural': '模擬揀料項目',
            },
        ),
    ]
