# Generated by Django 5.2.4 on 2026-03-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_picking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockpickingitem',
            name='quantity_picked',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='實際拿取數量'),
        ),
    ]
