# Generated by Django 5.2.4 on 2026-03-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_picking', '0002_mockpickingitem_quantity_picked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockPickingItem',
        ),
        migrations.DeleteModel(
            name='MockPickingTask',
        ),
    ]
