# Generated by Django 5.2.4 on 2026-03-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_picking', '0003_delete_mockpickingitem_delete_mockpickingtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouselocation',
            name='floor',
            field=models.IntegerField(default=1, help_text='預設為 1 樓', verbose_name='樓層'),
        ),
    ]
